server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yeb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.dong.server.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.dong.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 86400
  tokenHead: Bearer
